_core:
  default_config_hash: cteYTFHsidc-jJ8t9bxaGGe-7bRbvOMIH9vWxWm977k
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://large_1.png'
  use_default: false
example: foo
breadcrumbs_background:
  - '69'
