_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e322077a-c5d6-4462-8579-32f44a8ac25f
name: 'Pixelerant Technologies'
mail: sakshi55.sharma@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/4
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
